<<<<<<< HEAD
services:
  - type: web
    name: crypto-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
=======
services:
  - type: web
    name: crypto-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
>>>>>>> c6aaeb7fe75b8917757ce72b877b8003386fa0f7
